### ISSUE TITLE
Use deep copy there

### ISSUE THREAD

**Issue by hankai17** [sylar-yin/sylar#19]
https://github.com/sylar-yin/sylar/blob/94d7d2ca7a9284f1b03a20ac97e2ad208aaa4bd7/sylar/bytearray.cc#L55

**Comment by 4kangjc** [comment]
这里就是使用浅拷贝 使用bytearray操作别的内存

**Comment by hankai17** [comment]
@4kangjc 时间太长有点儿忘了 在跑http2 解析帧格式的时候会崩
