### ISSUE TITLE
协程不是为了异步代码同步化吗？引入协程是为了消除回调函数，为什么sylar里还有回调函数的存在？？？？

### ISSUE THREAD

**Issue by XiaoyuNoFish** [sylar-yin/sylar#38]

**Comment by Kaleido76** [comment]
我的个人理解哈，轻喷，或许协程的“消除回调函数”实际上本质目的是为了消除回调函数*链*而不是为了彻底消除回调函数？

**Comment by LunarStore** [comment]
看看muduo，再看看sylar，sylar消除回调指消除网络编程的回调，用户在用网络库的时候，你还需要写各种回调函数吗？直接同步编程就完了。完全不用回调就实现一个异步性能？你在做梦吗？
